sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PxgXvzkH6z2ctBias23vOzLPGTJ40rhwALBGqmYU2CaoTgw2cMm1bTD2vTjchLq1aiLLZCbZhXYnDk/gRgauLy1yqkhk/BVwvKhHw81PFQnXbDYKRC53lUgsk7F8z0fbHAazKoqaVWMvOucP81xL9VG8vrxoBiff5VDM0QQC274iNc3y6rgnC87sy90iJWPWEJSys7H5bqG+N8emO0G10Oa20QKwqHu+e6Oyp15HsX6t2xy5Wz9DHul3sD5Mm6VTdGemOTT5ta+1iuD4vzmh4Oq/G0K8ASIUR6AJYLWemqZmMK68DPVy6jVbP6NpQTjR7gyuvGPx12K0HuUhGfQKZflQJtUMGl4x6EDu8CNhdpHdcnKMs4GroL28v81gewc/rbzzWy4kFVJQaG5TkTHzkL4Uj5RZweW+uj3XxZSEv3tI2P1AHSvCU7l7iNGlW5RNXw/AqyPKPWV0Wg8j/31m2D8BUqRGeA71in10SPk9PnvGl49VMZs0d4EK0BXuUclw44gBDk1TzbxblzowAceueOP+wK/SxglWqRq1yTfxjFhvQhQftoz4LHCTIqLiQBjfTq2O1Wj/QQs55WfEvgK/ozB8F/vvpe/bi8f/wu90KUgIZpZhw6SQsTql5dFQZfFBDhe1SNnUYvXEoCL7lhhQXTrql73qz9E7Q7A+kmvC4nQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/Leaves-of-Grass_1322
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy